### ISSUE TITLE
SwitchNode breaks down after extensive looping

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#13]
Using an extensive loop over ~1000 elements (batch processing of multiple files) crashes the SwitchNode at seemingly random intervals.

``` console
Something bad happened in when executing Switch-5.
Input not set for node.
```

Timing problem?

**Comment by JLuebben** [comment]
Could be a synchronization issue. Can you try switching the comments in line 193 and 194 in runner.py. That way the interpreter will run all nodes in the main thread. If that solves the problem I know synchronization is the problem.

**Comment by k-eks** [comment]
Works perfectly without parallelization! Also, the node setup is done with a few seconds rather than a few minutes!

**Comment by JLuebben** [comment]
Interesting. Can you send me a screen shot of the node setup, too. That could be helpful for finding the bottleneck.

**Comment by k-eks** [comment]
Here you go (overview & detailed). As you see, more complex setups are possible :)
![screen shot 2016-09-23 at 16 41 46](https://cloud.githubusercontent.com/assets/12133169/18824919/fd66a74a-83c5-11e6-9d6b-6acec2d4d125.png)
![screen shot 2016-09-23 at 16 41 58](https://cloud.githubusercontent.com/assets/12133169/18824920/fd816bd4-83c5-11e6-9b5d-8f64550800a8.png)
![screen shot 2016-09-23 at 16 42 08](https://cloud.githubusercontent.com/assets/12133169/18824922/fd85f01e-83c5-11e6-85e0-1db200a6d167.png)
![screen shot 2016-09-23 at 16 42 24](https://cloud.githubusercontent.com/assets/12133169/18824921/fd8184ac-83c5-11e6-8b81-58a3f7488f72.png)



:

**Comment by JLuebben** [comment]
Thanks. I never tested larger setups.
I am currently on vacation. When I am back, I will probably need a dedicated Floppy fixing week..

**Comment by JLuebben** [comment]
I thought about this issue. There are definitively some problems with synchronization in the current version that I need to fix. But I also thought about changing concurrent node execution from 'opt-out' to 'opt-in' meaning that nodes won't be run concurrently by default but only when the node was decorated with an '@parallelNode' decorator. The previous idea was to have a '@sequentialNode' decorator for all nodes that are not supposed to run concurrently.

I consider this because a lot of nodes do trivial things like splitting a string, adding numbers, implement looping, etc. These nodes do not benefit from concurrency at all because the overhead added by creating threads for them is bigger than the benefit of having their own thread. In fact, in many cases there is no benefit at all.

If I choose the 'opt-in' approach, the person writing a node knows whether the global interpreter lock is released within the 'run' method and if it is the person can make that node run concurrently. 

I assume this would greatly improve performance for graphs that consist mainly of 'generic' nodes but I would like to get some feedback before changing things.

PS: I guess I could also implement something like a 'force concurrency' and/or 'force sequential execution' option for the interpreter to override node specific behavior.

**Comment by k-eks** [comment]
I gave this some thought and examined my larger setups. Most things run in a sequential manner anyways. There are some computational more expensive things, like breaking down a structure or sorting algorithms, and I think it should be up to the programmer to decide which parts can be reasonably done in parallel. Therefore, I think that the opt-in is probably the better way to go with things.

**Comment by JLuebben** [comment]
This should be fixed in newer versions. Older versions had synchronization issues that are fixed now.
New versions allow to switch between parallel and sequential execution mode via the settings menu.
