### ISSUE TITLE
How do you delete a node?

### ISSUE THREAD

**Issue by oregon-tony** [JLuebben/Floppy#23]
How do you delete a node once it is drawn out on the canvas? I see in the code (I'm not a Python expert..) where you have defined shortcuts like 'Ctrl-D', but selecting a node and hitting 'delete' key or Ctrl-D doesn't seem to delete the node. I'm on a Mac, Python 3.5, PyQt 5-5. The project is very awesome, thanks so much for sharing it. Tony.

**Comment by JLuebben** [comment]
I currently don't have the possibility to test Floppy on Mac platforms so any feedback is much appreciated. 
The latest commit simply adds the delete action to the very and of the main toolbar. Can you please check if selecting a node and then clicking on the toolbar button works. That way I'll know if the problem is related to the shortcut 'Ctrl+D' or if there are other issues.

**Comment by k-eks** [comment]
I've been using Floppy on a Mac ever since I came across it. I can delete a node by selecting it and press Cmd+D.

**Comment by oregon-tony** [comment]
Please close. I was looking at the code where it says Ctrl-D, but on a mac it is CMD-D as k-eks pointed out. Thanks.
