### ISSUE TITLE
WaitAny node does not work if the second pin is triggered

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#4]
The comments in the source code made clear that you think, that this is an unnecessary node but it is the only way I came up with to make an if-clause working properly. When the upper input pin is triggered, everything works fine, when the lower one is triggered, the console tells me "Input not set for node.", I could not identify the problem further :(
![screen shot 2016-09-15 at 16 11 05](https://cloud.githubusercontent.com/assets/12133169/18553537/154ec49a-7b61-11e6-8350-c0635438ba12.png)
(I have a setup up like this in mind to filter out hydrogen atoms. The shown setup was for my testing purposes.)

**Comment by JLuebben** [comment]
This is the intended solution for that problem. 
![switch](https://cloud.githubusercontent.com/assets/14290149/18555763/57650e2c-7b69-11e6-9a98-46f74362cb9a.jpeg)

It should work in your case but their might exist cases that I did not think about which is why I left the Node in. I will fix it for that purpose.
The idea behind dropping the WaitAny Node was that the Node responsible for branching the graph should also be the one taking care of the merging of the branches. If the branching and the merging Node are identical, it must have all information necessary to perform the merging.
