### ISSUE TITLE
Switch within a loop

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#9]
The Switch node gets stuck after a loop cycle. It seems to me that the switch is waiting for something which is the reason it is not executed.
![screen shot 2016-09-20 at 13 57 59](https://cloud.githubusercontent.com/assets/12133169/18669262/7142076c-7f3a-11e6-9d05-dfe2ce3369bb.png)
Console output:
```shel
Executing node ReadAtoms-0
Executing node CreateBool-5
Nothing to do here @ 1474372807.714685
File content not familiar. Relying of file name for file format.

1
Nothing to do here @ 1474372807.823233
2
Executing node ForEach-1
Executing node BreakAtom-2
Executing node Switch-4
Executing node FileWriter-3
Nothing to do here @ 1474372807.942647
Executing node WaitAny-6
Executing node Switch-4
Executing node ForEach-1
Executing node BreakAtom-2
```

**Comment by k-eks** [comment]
It either not working or I'm using it wrong (this time, probably the later). I've added a run function to the ForEach, this is the only difference to you main branch.
![screen shot 2016-09-20 at 18 21 19](https://cloud.githubusercontent.com/assets/12133169/18679456/f2e22084-7f5f-11e6-96ed-4dabf76a5a34.png)

**Comment by JLuebben** [comment]
I didn't think about the possibility to connect the node with itself. Currently, this does not work. I will think about a way to change that.

The reason is that after a Node was executed, the 'notify' method will set the inputs of all nodes that are connected to the outputs of the node that was executed. Next, the executed node will reset all its inputs. Unfortunately, for a node connected to itself, this means that the just set input will be reset.

There are several options to solve that problem. I will think about a good solution.

**Comment by k-eks** [comment]
I'm not sure if it is the self calling. The node setup in the picture also doesn't work, it stops again at the second run of the switch node. It seems that the switch node does not like to be executed twice.
![screen shot 2016-09-21 at 14 20 07](https://cloud.githubusercontent.com/assets/12133169/18710838/77a40498-8007-11e6-8e78-2fe44a34f9c6.png)
